### ISSUE TITLE
Utworzyć klasę Address

### ISSUE THREAD

**Issue by SylwesterNakonieczny** [PUW-Grupa1/Pracownicy#7]
Standardowe pola adresowe. Plik powinien należeć do pakietu model.

**Comment by SylwesterNakonieczny** [comment]
Uwagi - nazwy pól i zmiennych tworzymy z małej litery i stosujemy camelCase. W commicie stosujemy referencje do taska, w tym przypadku #7
Zipcode -> zipCode
dobry przykład żeby przetestować refaktoryzacje. W Intellij klikasz prawym na Zipcode wybierasz refactor->rename wprawadzasz nową nazwę i intellij zmieni wszystkie wywołania w projekcie z Zipcode na zipCode. Nie ma sensu otwierac nowego taska po prostu popraw to, commituj i wypchnija na serwer wpisując na końcu commit message #7

**Comment by PiotrMatenka** [comment]
Jeszcze parę poprawek zrobię, jak tylko trochę czasu znajdę, coś tam też porobiłem przy klasie Person

**Comment by PiotrMatenka** [comment]
zrobione
